### ISSUE TITLE
进度文件生成时获取checksum异常(hdfs)

### ISSUE THREAD

**Issue by datian9966** [apache/incubator-hugegraph-toolchain#132]
0.10.0版本中
在load hdfs上的文件时，由于hdfs集群的checksum处于disable状态，所以导致生成进度文件时获取checksum会产生异常，从而导致不能正常load。
针对此种情况，建议提供相关参数来控制
例如 如果彻底不需要断点续传功能，可否不生成进度文件
或者 hdfs那里的checksum生成方式在特殊情况时使用别的生成方式,不从hdfs上取checksum

**Comment by lanerbean** [comment]
您好，我在使用1.0.0版本时，尝试从HDFS加载数据，也遇到了无法获取hdfs的checksum的问题，请问该如何解决？有什么配置需要设置吗？
![1682675828536](https://user-images.githubusercontent.com/18582787/235117418-6995356e-3a48-46c8-9bc5-18c1386fe89c.png)

**Comment by imbajin** [comment]
fixed in #454
