### ISSUE TITLE
我如何用nginx代理hugegraph-hubble

### ISSUE THREAD

**Issue by ZilinCui** [apache/incubator-hugegraph-toolchain#261]
### Before submit

- [X] 我已经确认现有的 [Issues](https://github.com/hugegraph/hugegraph/issues) 与 [FAQ](https://hugegraph.github.io/hugegraph-doc/guides/faq.html) 中没有相同 / 重复问题

### Environment (环境信息)

- Server Version: v0.11.x
- Backend: RocksDB x nodes, HDD or SSD 
- OS: xx CPUs, xx G RAM, Centos 7.x 
- Data Size:  xx vertices, xx edges 

### Your Question (问题描述)

我如何用nginx代理hugegraph-hubble

### Vertex/Edge example (问题点 / 边数据举例)

```javascript
我如何用nginx代理hugegraph-hubble
```

### Schema [VertexLabel, EdgeLabel, IndexLabel] (元数据结构)

```javascript
我如何用nginx代理hugegraph-hubble
```

**Comment by imbajin** [comment]
不太明白需求, 代理是指的啥? 
- 正向
- 反向
- 静态 html?

**Comment by ZilinCui** [comment]
比如说hugegraph-hubble的端口是8088，我现在nginx代理了9090端口，我想通过9090端口去访问hugegraph-hubble.

`server{
    listen 9090;

    location /hubble {
           proxy_pass http://localhost:8088;
    }
}`

**Comment by imbajin** [comment]
这个是 nginx 使用相关问题呢, 和图本身关系不大了. 可以查阅一下 nginx 文档/issue
