### ISSUE TITLE
[Question] 当我使用hdfs导入时提示 Failed to load, cause: java.net.UnknownHostException: abc

### ISSUE THREAD

**Issue by waynecookie** [apache/incubator-hugegraph-toolchain#301]
### Before submit

- [x] 我已经确认现有的 [Issues](https://github.com/hugegraph/hugegraph/issues) 与 [FAQ](https://hugegraph.github.io/hugegraph-doc/guides/faq.html) 中没有相同 / 重复问题

### Environment (环境信息)

- Server Version: v0.12.x
- Backend: RocksDB x nodes, HDD or SSD 
- OS: xx CPUs, xx G RAM, Centos 7.x 
- Data Size:  xx vertices, xx edges 

### Your Question (问题描述)

请教一下
从hdfs（设置了ha）中导入数据，fs.defaultFS 为 hdfs://abc,
当我执行导入时提示 
```
Failed to load, cause: java.net.UnknownHostException: abc
```
1、请问这是什么原因?
2、当我改为hdfs://ip:port模式时可以了，那一定需要这样的模式吗？发生故障时，ip 可能会变为另一个stanby状态的ip

**Comment by imbajin** [comment]
这是 hdfs 的经典老问题了把...跟 loader 本身没多少关系. 你可以搜一下那个报错加上 hdfs, 有几个可能的解决方案 (分高低不同版本)

**Comment by waynecookie** [comment]
> 

指条明路？我搜索到的都是说hdfs格式化错误，要不然就是 在/etc/hosts 这个文件上添加配置就行了，可是这并不能解决

**Comment by waynecookie** [comment]
> 这是 hdfs 的经典老问题了把...跟 loader 本身没多少关系. 你可以搜一下那个报错加上 hdfs, 有几个可能的解决方案 (分高低不同版本)

指条明路？我搜索到的都是说hdfs格式化错误，要不然就是 在/etc/hosts 这个文件上添加配置就行了，可是这并不能解决

**Comment by imbajin** [comment]
> > 这是 hdfs 的经典老问题了把...跟 loader 本身没多少关系. 你可以搜一下那个报错加上 hdfs, 有几个可能的解决方案 (分高低不同版本)
> 
> 指条明路？我搜索到的都是说hdfs格式化错误，要不然就是 在/etc/hosts 这个文件上添加配置就行了，可是这并不能解决

好像是有两个参数, 可以控制是否允许非 ip 写法还有一个是否支持虚拟域名. 或者你去 hdfs 的 issue/jira 里搜索一下, 我想肯定有靠谱的回答

**Comment by simon824** [comment]
@waynecookie 有没有配置 `core-site.xml` 的路径，参考：https://hugegraph.apache.org/cn/docs/quickstart/hugegraph-loader/#3322-hdfs-%E8%BE%93%E5%85%A5%E6%BA%90

**Comment by waynecookie** [comment]
您好，已收到您的邮件

**Comment by waynecookie** [comment]
> @waynecookie 有没有配置 `core-site.xml` 的路径，参考：https://hugegraph.apache.org/cn/docs/quickstart/hugegraph-loader/#3322-hdfs-%E8%BE%93%E5%85%A5%E6%BA%90

这是有设置的
