### ISSUE TITLE
[Bug]  Import Chinese meet bad encode with csv file in hubble (乱码)

### ISSUE THREAD

**Issue by javeme** [apache/incubator-hugegraph-toolchain#302]
### Bug Type (问题类型)

dashboard render (前端渲染问题)

### Before submit

- [X] I had searched in the [issues](https://github.com/hugegraph/hugegraph-loader/issues) and found no similar issues.

### Environment (环境信息)

- Server Version: v0.12.x
- Loader Version: v0.12.x
- Data Size:  xx vertices, xx edges 

### Expected & Actual behavior (期望与实际表现)

copied from https://github.com/hugegraph/hugegraph-hubble/issues/355

**Comment by imbajin** [comment]
@wanganjuan not sure is it a fe problem?

**Comment by wanganjuan** [comment]
> @wanganjuan not sure is it a fe problem?
i test is ok
![image](https://user-images.githubusercontent.com/10061479/204123436-de3d6161-129b-4c58-92c7-48cee46b48fc.png)

![image](https://user-images.githubusercontent.com/10061479/204123427-7c4109c4-754c-46a1-89eb-25bad614ae9e.png)

**Comment by wanganjuan** [comment]
> @wanganjuan not sure is it a fe problem?

If you reproduce the problem, please contact me and give me test files.

**Comment by imbajin** [comment]
> > @wanganjuan not sure is it a fe problem?
> 
> If you reproduce the problem, please contact me and give me test files.

@ZilinCui @b1tkeeper could u upload or leave a test file, thanks (and with the browser & hubble version)

**Comment by simon824** [comment]
- hugegraph-1.2.0
- hubble-1.2.0
For Chinese property fields, click `Edit` without making any changes and then click `Save`, the Chinese will become garbled.

![image](https://github.com/apache/incubator-hugegraph-toolchain/assets/18065113/4226c6f3-463f-4aad-9da3-fd45a8c6ea92)
![image](https://github.com/apache/incubator-hugegraph-toolchain/assets/18065113/0c95aba1-0762-46e6-9ae1-985f63436408)
