### ISSUE TITLE
[Bug] hugegraph导入hdfs的空值时，若hdfs为text file则成功，若为ORC则失败

### ISSUE THREAD

**Issue by jyyhao** [apache/incubator-hugegraph-toolchain#319]
### Bug Type (问题类型)

exception / error (异常报错)

### Before submit

- [X] I had searched in the [issues](https://github.com/hugegraph/hugegraph-loader/issues) and found no similar issues.

### Environment (环境信息)

- Server Version: hugegraph-0.11.2
- Loader Version: hugegraph-loader-0.11.1

### Expected & Actual behavior (期望与实际表现)

![26d3576017cbefbc6df35e5a19b2f8b](https://user-images.githubusercontent.com/35911970/182508297-9dd189e8-2bb8-4539-bd0c-705861761832.jpg)

**Comment by zhoney** [comment]
fixed in https://github.com/apache/incubator-hugegraph-toolchain/pull/320

**Comment by jyyhao** [comment]
已解决，感谢大佬
