### ISSUE TITLE
[Bug] tools 1.0.0 Java11 运行报错 (java8正常)

### ISSUE THREAD

**Issue by shangrilaxie** [apache/incubator-hugegraph-toolchain#407]
### Bug Type (问题类型)

others (please comment below)

### Before submit

- [X] I had searched in the [issues](https://github.com/apache/hugegraph-toolchain/issues) and found no similar issues.

### Environment (环境信息)

- Server Version: v1.x.x
- Toolchain Version: v1.x.x
- Data Size:  xx vertices, xx edges 

### Expected & Actual behavior (期望与实际表现)

期望tools正常启动。实际是当转化为jdk11环境时，错误提示：不支持。

**Comment by imbajin** [comment]
感谢反馈，给一下具体的下载地址，以及你下的二进制包还是源码包，麻烦给一下对应的 sha512 值

另外，方便的话可以直接截个报错图进来看看

**Comment by imbajin** [comment]
@shangrilaxie fixed 

你可以试试重新下载一下二进制包试试(URL 不变), 注意确认一下 hash 值(sha512)如下就是最新的:
`bc72cb74771f09cc7e079d21cab6eb731245f0f1fcf0368bd8a938a971e2366016d1fd842e4447a592ee8ae80697a4342754f2a5d942d923a4c9e58b251032dc  apache-hugegraph-toolchain-incubating-1.0.0.tar.gz`
