### ISSUE TITLE
用可视化工具导入csv格式数据时，第一次执行会报错 #### PARSE ERROR: Failed to convert value(key=age) 'age'(class java.lang.String) to Number  addr,age,name

### ISSUE THREAD

**Issue by cygoodboy** [apache/incubator-hugegraph-toolchain#413]
### Problem Type (问题类型)

other exception / error (其他异常报错)

### Before submit

- [X] 我已经确认现有的 [Issues](https://github.com/hugegraph/hugegraph/issues) 与 [FAQ](https://hugegraph.github.io/hugegraph-doc/guides/faq.html) 中没有相同 / 重复问题

### Environment (环境信息)

- Server Version: v0.11.x
- OS: xx CPUs, xx G RAM, Centos 7.x 
- Data Size:  5 vertices

### Your Question (问题描述)

用可视化工具导入csv格式数据时，第一次执行会报错，失败后点继续才能导入成功  #### PARSE ERROR: Failed to convert value(key=age) 'age'(class java.lang.String) to Number  addr,age,name

**Comment by imbajin** [comment]
你发的图都看不到, 需要重新发一下, 另外使用一下最新 apache 1.0 版看看情况
