### ISSUE TITLE
[Bug] Hubble 界面编辑顶点类型时顶点样式无法展示颜色

### ISSUE THREAD

**Issue by javeme** [apache/incubator-hugegraph-toolchain#422]
### Bug Type (问题类型)

dashboard render (前端渲染问题)

### Before submit

- [X] I had searched in the [issues](https://github.com/apache/hugegraph-toolchain/issues) and found no similar issues.

### Environment (环境信息)

- Server Version: 1.0.0
- Toolchain Version: 1.0.0

### Expected & Actual behavior (期望与实际表现)

<img width="351" alt="vl 2023-01-14 00 45 40" src="https://user-images.githubusercontent.com/9625821/212374111-038ac37e-ebb1-44ea-981f-9b65ea9f2c92.png">

**Comment by imbajin** [comment]
@wanganjuan could u help to check it? thanks

**Comment by wanganjuan** [comment]
> @wanganjuan could u help to check it? thanks

fixed https://github.com/apache/incubator-hugegraph-toolchain/pull/423
