### ISSUE TITLE
[Enhancement] keep hadoop-hdfs-client and hadoop-common version consistent

### ISSUE THREAD

**Issue by simon824** [apache/incubator-hugegraph-toolchain#456]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-hugegraph-toolchain/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Feature Description (功能描述)

refer to  #454 
hadoop-common 3.3.1
hadoop-hdfs-client 2.10.1

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by imbajin** [comment]
maybe unify them with one version like `${hdfs.version}`

**Comment by chenlixuan** [comment]
I can help to improve it.
