### ISSUE TITLE
[Enhancement] unify the dependencies versions of the entire project

### ISSUE THREAD

**Issue by simon824** [apache/incubator-hugegraph-toolchain#458]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-hugegraph-toolchain/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Feature Description (功能描述)

refer to https://github.com/apache/incubator-hugegraph-toolchain/pull/457#discussion_r1189281984

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by simon824** [comment]
@chenlixuan

**Comment by conghuhu** [comment]
@imbajin 
I'm interested in this issue, is it convenient to provide more information?
I would like to know in which project we are going to unify the dependencies versions.

**Comment by imbajin** [comment]
> @imbajin I'm interested in this issue, is it convenient to provide more information? I would like to know in which project we are going to unify the dependencies versions.

the root pom of toolchain, client / loader / hubble / tools were separated before, so they import a lot of duplicate dependencies (and the version may also be different), we need to refactor them (subtask of #399, you could update/rebase the PR to the latest & continue to finish it)

**Comment by conghuhu** [comment]
plz assgin to me, thx
