### ISSUE TITLE
[Bug] hugegraph-spark-loader脚本执行EXEC 命令时可能触发长度限制

### ISSUE THREAD

**Issue by haohao0103** [apache/incubator-hugegraph-toolchain#460]
### Bug Type (问题类型)

None

### Before submit

- [X] I had searched in the [issues](https://github.com/apache/hugegraph-toolchain/issues) and found no similar issues.

### Environment (环境信息)

- Server Version: v1.0.0
- Toolchain Version: v1.0.0
- Data Size:  xx vertices, xx edges 

### Expected & Actual behavior (期望与实际表现)

error message:
` --graph hugegraph --batch-size 1499 --host 10.136.29.143 --port 8080 --execute-date 2023-05-11 --sink-type false  --vertex-partitions 120 --edge-partitions 120 --graph-type entity --file /xxx/vertexs-struct.json: **cannot execute: File name too long**
`
hugegraph-spark-loader.sh:
....
echo "${CMD}"
exec "${CMD}"

The above error message will be reported when executing exec "${CMD}"，My solution is to remove the double quotes,See if the community has a better solution, thanks

**Comment by gaoyuan5251** [comment]
@simon824 hi bro, i want to fix it , can you assigned it to me？
