### ISSUE TITLE
[Feature] bypass server for hbase bulk delete massive vertices and edges

### ISSUE THREAD

**Issue by haohao0103** [apache/incubator-hugegraph-toolchain#488]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-hugegraph-toolchain/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Feature Description (功能描述)

1、Support  delete massive vertices and edges  bypass server
2、Just support customString and customNumber ID now;
The  feature has been launched internally.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by imbajin** [comment]
already done for it

**Comment by haohao0103** [comment]
@imbajin hello, which branch is this PR merged into? thanks

**Comment by imbajin** [comment]
> @imbajin hello, which branch is this PR merged into? thanks

Perhaps it hasn't been resolved, you can reopen it
