### ISSUE TITLE
[Bug] Create HugeClient but return null

### ISSUE THREAD

**Issue by feitao1993** [apache/incubator-hugegraph-toolchain#492]
### Problem Type (问题类型)

None

### Before submit

- [X] 我已经确认现有的 [Issues](https://github.com/apache/hugegraph/issues) 与 [FAQ](https://hugegraph.apache.org/docs/guides/faq/) 中没有相同 / 重复问题 (I have confirmed and searched that there are no similar problems in the historical issue and documents)

### Environment (环境信息)

- Client Version: 1.0.0 (Apache Release Version)
- springboot 3.1.1
- jdk17

### Your Question (问题描述)

在使用HugeClient.builder(url, graph).build创建hugeClient时，总是得到null

**Comment by z7658329** [comment]
经线下确认排查 是由于项目依赖fastjson所致，fastjson问题可以参考历史issue：[#5](https://github.com/apache/incubator-hugegraph/issues/5)
