### ISSUE TITLE
[Bug]  Exception Occurs When Running hugegraph-loader.sh Script from the HugeGraph official tutorial.

### ISSUE THREAD

**Issue by Zony7** [apache/incubator-hugegraph-toolchain#509]
### Bug Type (问题类型)

exception / error (异常报错)

### Before submit

- [X] I had searched in the [issues](https://github.com/apache/hugegraph-toolchain/issues) and found no similar issues.

### Environment (环境信息)

- Server Version: v1.0.0
- Toolchain Version: v1.0.0
- Data Size: 8 vertices, 6 edges
- Operating System: Ubuntu 22.04
- Shell Interpreter: sh (also tried bash)

### Expected & Actual behavior (期望与实际表现)

Issue Description: I'm encountering an unexpected behavior when attempting to run the hugegraph-loader.sh script from the HugeGraph official tutorial. The issue seems to be specific to different shell environments.
Command Example:
`$ sh bin/hugegraph-loader.sh -g hugegraph -f example/file/struct.json -s example/file/schema.groovy`
When executing the above command using the sh shell, I encounter the following exceptions:
```
hugegraph-loader.sh: 19: Bad substitution
hugegraph-loader.sh: 37: set: Illegal option -o pipefail

```
Attempted Solutions:

The command runs successfully using the bash shell.

**Comment by liuxiaocs7** [comment]
solved by #509, if there are other questions, please reopen.
