### ISSUE TITLE
[Bug] HG hubble build fail

### ISSUE THREAD

**Issue by haohao0103** [apache/incubator-hugegraph-toolchain#513]
### Bug Type (问题类型)

exception / error (异常报错)

### Before submit

- [X] I had searched in the [issues](https://github.com/apache/hugegraph-toolchain/issues) and found no similar issues.

### Environment (环境信息)

- Server Version: v1.0.0
- Toolchain Version: v1.0.0

### Expected & Actual behavior (期望与实际表现)

build cmd:
mvn clean package

error msg:
main:
     [exec] Current OS is Mac OS X
     [exec] Executing 'bash' with arguments:
     [exec] './dist.sh'
     [exec] 
     [exec] The ' characters around the executable and arguments are
     [exec] not part of the command.
Execute:Java13CommandLauncher: Executing 'bash' with arguments:
'./dist.sh'

The ' characters around the executable and arguments are
not part of the command.
     [exec] yarn install v1.22.19
     [exec] [1/4] Resolving packages...
     [exec] success Already up-to-date.
     [exec] Done in 0.58s.
     [exec] yarn run v1.22.19
     [exec] $ react-app-rewired build && npm run license
     [exec] The following changes are being made to your tsconfig.json file:
     [exec]   - compilerOptions.paths must not be set (aliased imports are not supported)
     [exec] 
     [exec] Creating an optimized production build...
     [exec] <s> [webpack.Progress] 0% compiling
     [exec] <s> [webpack.Progress] 10% building 0/0 modules 0 active 
     [exec] <s> [webpack.Progress] 10% building 0/1 modules 1 active multi /xxx/xx//hugegraph-toolchain/incubator-hugegraph-toolchain/hugegraph-hubble/hubble-fe/src/index.tsx
     [exec] <s> [webpack.Progress] 10% building 1/1 modules 0 active 
     [exec] Error: error:0308010C:digital envelope routines::unsupported
     [exec]     at new Hash (node:internal/crypto/hash:69:19)
     [exec]     at Object.createHash (node:crypto:138:10)
     [exec]     at module.exports (/xxx/xx//hugegraph-toolchain/incubator-hugegraph-toolchain/hugegraph-hubble/hubble-fe/node_modules/webpack/lib/util/createHash.js:135:53)
     [exec]     at NormalModule._initBuildHash (/xxx/xx//hugegraph-toolchain/incubator-hugegraph-toolchain/hugegraph-hubble/hubble-fe/node_modules/webpack/lib/NormalModule.js:417:16)
     [exec]     at handleParseError (/xxx/xx//hugegraph-toolchain/incubator-hugegraph-toolchain/hugegraph-hubble/hubble-fe/node_modules/webpack/lib/NormalModule.js:471:10)
     [exec]     at /xxx/xx//hugegraph-toolchain/incubator-hugegraph-toolchain/hugegraph-hubble/hubble-fe/node_modules/webpack/lib/NormalModule.js:503:5
     [exec]     at /xxx/xx//hugegraph-toolchain/incubator-hugegraph-toolchain/hugegraph-hubble/hubble-fe/node_modules/webpack/lib/NormalModule.js:358:12
     [exec]     at /xxx/xx//hugegraph-toolchain/incubator-hugegraph-toolchain/hugegraph-hubble/hubble-fe/node_modules/loader-runner/lib/LoaderRunner.js:373:3
     [exec]     at iterateNormalLoaders (/xxx/xx//hugegraph-toolchain/incubator-hugegraph-toolchain/hugegraph-hubble/hubble-fe/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
     [exec]     at iterateNormalLoaders (/xxx/xx//hugegraph-toolchain/incubator-hugegraph-toolchain/hugegraph-hubble/hubble-fe/node_modules/loader-runner/lib/LoaderRunner.js:221:10)
     [exec] <s> [webpack.Progress] 10% building 1/2 modules 1 active /xxx/xx//hugegraph-toolchain/incubator-hugegraph-toolchain/hugegraph-hubble/hubble-fe/node_modules/react-scripts/node_modules/babel-loader/lib/index.js??ref--6-oneOf-1!/xxx/xx//hugegraph-toolchain/incubator-hugegraph-toolchain/hugegraph-hubble/hubble-fe/node_modules/eslint-loader/dist/cjs.js??ref--5-0!/xxx/xx//hugegraph-toolchain/incubator-hugegraph-toolchain/hugegraph-hubble/hubble-fe/src/index.tsx
     [exec] info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
     [exec] /xxx/xx//hugegraph-toolchain/incubator-hugegraph-toolchain/hugegraph-hubble/hubble-fe/node_modules/react-scripts/scripts/build.js:19
     [exec]   throw err;
     [exec]   ^
     [exec] 
     [exec] Error: error:0308010C:digital envelope routines::unsupported
     [exec]     at new Hash (node:internal/crypto/hash:69:19)
     [exec]     at Object.createHash (node:crypto:138:10)
     [exec]     at module.exports (/xxx/xx//hugegraph-toolchain/incubator-hugegraph-toolchain/hugegraph-hubble/hubble-fe/node_modules/webpack/lib/util/createHash.js:135:53)
     [exec]     at NormalModule._initBuildHash (/xxx/xx//hugegraph-toolchain/incubator-hugegraph-toolchain/hugegraph-hubble/hubble-fe/node_modules/webpack/lib/NormalModule.js:417:16)
     [exec]     at /xxx/xx//hugegraph-toolchain/incubator-hugegraph-toolchain/hugegraph-hubble/hubble-fe/node_modules/webpack/lib/NormalModule.js:452:10
     [exec]     at /xxx/xx//hugegraph-toolchain/incubator-hugegraph-toolchain/hugegraph-hubble/hubble-fe/node_modules/webpack/lib/NormalModule.js:323:13
     [exec]     at /xxx/xx//hugegraph-toolchain/incubator-hugegraph-toolchain/hugegraph-hubble/hubble-fe/node_modules/loader-runner/lib/LoaderRunner.js:367:11
     [exec]     at /xxx/xx//hugegraph-toolchain/incubator-hugegraph-toolchain/hugegraph-hubble/hubble-fe/node_modules/loader-runner/lib/LoaderRunner.js:233:18
     [exec]     at context.callback (/xxx/xx//hugegraph-toolchain/incubator-hugegraph-toolchain/hugegraph-hubble/hubble-fe/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
     [exec]     at /xxx/xx//hugegraph-toolchain/incubator-hugegraph-toolchain/hugegraph-hubble/hubble-fe/node_modules/react-scripts/node_modules/babel-loader/lib/index.js:59:103 {
     [exec]   opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
     [exec]   library: 'digital envelope routines',
     [exec]   reason: 'unsupported',
     [exec]   code: 'ERR_OSSL_EVP_UNSUPPORTED'
     [exec] }
     [exec] 
     [exec] Node.js v20.5.1
     [exec] error Command failed with exit code 1.

I have asked gpt:
<img width="1097" alt="image" src="https://github.com/apache/incubator-hugegraph-toolchain/assets/30570711/1d7fd431-c8db-4029-a38a-4f5e17030d1b">

I modified it according to gpt's suggestions, and now it can work. Because I am not very good at the front end, please help to confirm whether there is a better plan or suggestion

### Vertex/Edge example (问题点 / 边数据举例)

```javascript
null
```

**Comment by imbajin** [comment]
@liuxiaocs7 , we could refer this PR https://github.com/apache/incubator-hugegraph/pull/2277 to check/install proper `yarn` env & avoid hard code `dist.sh` in maven pom?
