### ISSUE TITLE
HugeGraph-Loader 执行命令导入 设置–max-parse-errors出错

### ISSUE THREAD

**Issue by songlf1002** [apache/incubator-hugegraph-toolchain#518]
### Bug Type (问题类型)

exception / error (异常报错)

### Before submit

- [X] I had searched in the [issues](https://github.com/apache/hugegraph-toolchain/issues) and found no similar issues.

### Environment (环境信息)

- Server Version:  v0.12.0
- Toolchain Version: v0.12.0

### Expected & Actual behavior (期望与实际表现)

期望：HugeGraph-Loader 执行命令导入 可以对max-parse-errors进行设置
实际：
![image](https://github.com/apache/incubator-hugegraph-toolchain/assets/70573089/96603bd4-214b-414b-9d2a-9dfb016121d1)

**Comment by simon824** [comment]
@songlf1002  please use `--max-parse-errors` instead
