### ISSUE TITLE
[Bug] Api version of client is outdated

### ISSUE THREAD

**Issue by aroundabout** [apache/incubator-hugegraph-toolchain#545]
### Bug Type (问题类型)

exception / error (异常报错)

### Before submit

- [X] I had searched in the [issues](https://github.com/apache/hugegraph-toolchain/issues) and found no similar issues.

### Environment (环境信息)

- Server Version: v1.5.0
- Client Version: v1.0.0

### Expected & Actual behavior (期望与实际表现)

![img_v3_025q_048c7ab3-5819-4019-bbde-3d27d9d5b0cg](https://github.com/apache/incubator-hugegraph-toolchain/assets/49650772/d284f3ef-4564-4a38-ac33-d771d9e32929)
The api version mismatch between client and server.

The bug is caused by the update of api version in server:
[    public static final Version VERSION = Version.of(ApiVersion.class, "0.71");](https://github.com/apache/incubator-hugegraph/blob/20d1e5228e39bd974079891fc713574fb14798c5/hugegraph-server/hugegraph-api/src/main/java/org/apache/hugegraph/version/ApiVersion.java#L125)
![image](https://github.com/apache/incubator-hugegraph-toolchain/assets/49650772/b813780b-8f73-4d64-8c01-890e43709376)
While the api version is between 0.38-0.70 in client:
![7ae957869e71698f16587182d260b64](https://github.com/apache/incubator-hugegraph-toolchain/assets/49650772/92dda988-d021-423e-9014-63d7cd9a23dd)

**Comment by liuxiaocs7** [comment]
related pr: https://github.com/apache/incubator-hugegraph-toolchain/pull/542
