### ISSUE TITLE
[Bug] ToolChain build fails

### ISSUE THREAD

**Issue by liuxiaocs7** [apache/incubator-hugegraph-toolchain#547]
### Bug Type (问题类型)

None

### Before submit

- [X] I had searched in the [issues](https://github.com/apache/hugegraph-toolchain/issues) and found no similar issues.

### Environment (环境信息)

- Server Version: v1.x.x
- Toolchain master
- Data Size:  xx vertices, xx edges 

### Expected & Actual behavior (期望与实际表现)

![image](https://github.com/apache/incubator-hugegraph-toolchain/assets/42756849/07193375-7361-4bfa-973f-313ca4b071f4)

**Comment by imbajin** [comment]
yes, we need `-P stage` now due to the stage dependencies

https://github.com/apache/incubator-hugegraph-toolchain/blob/cb68beac76b9d0492054bade87cdfccbb3ae15bf/pom.xml#L372
