### ISSUE TITLE
[Question] Import data with Loader in RocksDB & MySQL(meet error) 

### ISSUE THREAD

**Issue by SkrDrag** [apache/incubator-hugegraph-toolchain#569]
### Problem Type (问题类型)

None

### Before submit

- [X] 我已经确认现有的 [Issues](https://github.com/apache/hugegraph/issues) 与 [FAQ](https://hugegraph.apache.org/docs/guides/faq/) 中没有相同 / 重复问题 (I have confirmed and searched that there are no similar problems in the historical issue and documents)

### Environment (环境信息)

- Server Version: 1.5.0 (Apache Release Version)
- Backend: Mysql
- OS: xx CPUs, xx G RAM, Ubuntu 2x.x / CentOS 7.x 
- Data Size:  xx vertices, xx edges 

### Your Question (问题描述)

我一开始选择的后端是Rocksdb，且数据库和Server在同一台机器上。数据导入时没有问题。
之后我选择在另一台机器上存储后端数据库mysql，通过配置Server远程连接mysql数据库，初始化成功并成功启动Server。我在存储数据库的机器上使用loader导入数据，报错

运行脚本:
`bin/hugegraph-loader.sh -g hugegraph -f /home/llw/dataset/struct.json -s /home/llw/dataset/schema.groovy -h`

```java
210.xx.xx.72 
日志：
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/home/llw/apache-hugegraph-toolchain-incubating-1.2.0/apache-hugegraph-loader-incubating-1.2.0/lib/log4j-slf4j-impl-2.18.0.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/home/llw/apache-hugegraph-toolchain-incubating-1.2.0/apache-hugegraph-loader-incubating-1.2.0/lib/apache-hugegraph-loader-incubating-1.2.0-shaded.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/home/llw/apache-hugegraph-toolchain-incubating-1.2.0/apache-hugegraph-loader-incubating-1.2.0/lib/slf4j-log4j12-1.7.25.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.apache.logging.slf4j.Log4jLoggerFactory]
WARNING: sun.reflect.Reflection.getCallerClass is not supported. This will impact performance.
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.codehaus.groovy.reflection.CachedClass (file:/home/llw/apache-hugegraph-toolchain-incubating-1.2.0/apache-hugegraph-loader-incubating-1.2.0/lib/apache-hugegraph-loader-incubating-1.2.0-shaded.jar) to method java.lang.Object.finalize()
WARNING: Please consider reporting this to the maintainers of org.codehaus.groovy.reflection.CachedClass
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

Failed to load, cause: Not all index fields '[id]' are contained in schema properties '[ID, CODE, NAME, TYPE, length]'
```

我的问题：
1.我期望Server和后端数据库在两个不同的结点上，如何使用loader向数据库中导入数据，正确的步骤是什么。
2.报这个错误是因为映射文件错误吗？应该如何修改？

```groovy
schema.groovy:
schema.propertyKey("ID").asText().ifNotExist().create();
schema.propertyKey("CODE").asText().ifNotExist().create();
schema.propertyKey("NAME").asText().ifNotExist().create();
schema.propertyKey("TYPE").asText().ifNotExist().create();

schema.propertyKey("id").asText().ifNotExist().create();
schema.propertyKey("code").asText().ifNotExist().create();
schema.propertyKey("name").asText().ifNotExist().create();
schema.propertyKey("type").asText().ifNotExist().create();
schema.propertyKey("aid").asText().ifNotExist().create();
schema.propertyKey("zid").asText().ifNotExist().create();
schema.propertyKey("length").asFloat().ifNotExist().create();


schema.vertexLabel("device")
      .properties("ID","CODE","NAME","TYPE")
      .primaryKeys("ID")
      .nullableKeys("NAME")
      .ifNotExist()
      .create();


schema.edgeLabel("link")
      .sourceLabel("device")
      .targetLabel("device")
      .properties("id","code","name","type","length")
      .nullableKeys("code","name","type")
      .ifNotExist()
      .create();

schema.indexLabel("personByCityAndAge").
      onE("link").
      by("length").
      range().
      ifNotExist()
      .create();

schema.indexLabel("deviceByType")
      .onV("device")
      .by("TYPE")
      .secondary()
      .ifNotExist()
      .create();

schema.indexLabel("linkByType")
      .onE("link")
      .by("id")
      .secondary()
      .ifNotExist()
      .create();

struct .json:

{
  "vertices": [
    {
      "label": "device",
      "input": {
        "type": "file",
        "path": "/home/llw/dataset/dev.csv",
        "header": ["ID","CODE","NAME","TYPE"],
        "format": "CSV",
        "charset": "UTF-8"
      }
    }
  ],
  "edges": [
    {
      "label": "link",
      "source": ["aid"],
      "target": ["zid"],
      "input": {
        "type": "file",
        "path": "/home/llw/dataset/link.csv",
        "format": "CSV",
        "header":["id","code","name","type","aid","zid","length"]
      },
      "field_mapping": {
        "aid": "ID",
        "zid": "ID"
      }
    },
    {
      "label": "link",
      "source": ["zid"],
      "target": ["aid"],
      "input": {
        "type": "file",
        "path": "/home/llw/dataset/link.csv",
        "format": "CSV",
        "header":["id","code","name","type","aid","zid","length"]
      },
      "field_mapping": {
        "aid": "ID",
        "zid": "ID"
      }
    }
  ]
  
}
```

**Comment by imbajin** [comment]
@dosu-bot 这是一个 toolchain 仓库 loader 模块的问题, 请你结合当前仓库的代码/ issue / 文档上下文来重新进行回答

文档可以参考: 
1. https://github.com/apache/incubator-hugegraph-doc/blob/master/content/cn/docs/quickstart/hugegraph-loader.md
2. https://hugegraph.apache.org/docs/quickstart/hugegraph-loader/

---

另外 @SkrDrag ,感谢你的关注和提问, 也感谢你愿意和我们新引入的 LLM 🤖 进行对话, 一些小建议:
1. 提交 issue 的时候选择正确的分类, `Question` 请不要用 `Bug` 分类提交, 这会引入错误的 label 需要人工修改
2. 保留 `[Question]` 这个分类 title 前缀, 不要删除它, 尽可能用英文标题, 这样方便其他人搜索/查询 (内容如果方便的话用英文当然更好, 如果觉得麻烦可以选择自己习惯的语言)
3. 回复 dosu 机器人的时候可以 `@` 一下它, 就像我上面那样, 这样可能它感知和回复的语言更加一致, 你可以给更多的描述词/指令/refer 帮助它更好的学习和寻找答案

**Comment by SkrDrag** [comment]
> @dosu-bot 这是一个 toolchain 仓库 loader 模块的问题, 请你结合当前仓库的代码/ issue / 文档上下文来重新进行回答, 希望以后类似的问题, 你可以从 `server` 仓库感知到提醒用户/社区管理员进行 transfer, 若暂不支持, 这也是一个未来可以实现的 feature~
> 
> 文档可以参考:
> 
> 1. https://github.com/apache/incubator-hugegraph-doc/blob/master/content/cn/docs/quickstart/hugegraph-loader.md
> 2. https://hugegraph.apache.org/docs/quickstart/hugegraph-loader/
> 
> 另外 @SkrDrag ,感谢你的关注和提问, 也感谢你愿意和我们新引入的 LLM 🤖 进行对话, 欢迎继续使用, 有一点小建议:
> 
> 1. 提交 issue 的时候选择正确的分类, `Question` 请不用 `Bug` 分类提交, 这会引入不正确的 label, 需要社区人工修改
> 2. 保留 `[Question]` 这个分类 title 前缀, 不要删除它, 尽可能用英文标题, 这样方便其他人搜索/查询 (内容如果方便的话用英文当然更好, 如果觉得麻烦可以选择自己习惯的语言)
> 3. 回复 dosu 机器人的时候可以 `@` 一下它, 就像我上面那样, 这样可能它感知和回复的语言更加一致, 你可以给更多的描述词/指令/refer 帮助它更好的学习和寻找答案
> 4. 贴错误和命令/日志/schema 的时候, 如果比较长建议用 ```java 这样的代码块标记包围(单行/多行), 这样阅读体验对大家都会好很多, 也会有更多的同学愿意帮助检查确认(如图)
> 
> <img alt="image" width="666" src="https://private-user-images.githubusercontent.com/17706099/296693137-adbd5247-9546-4b67-b088-510f58878fad.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUzMTc5ODksIm5iZiI6MTcwNTMxNzY4OSwicGF0aCI6Ii8xNzcwNjA5OS8yOTY2OTMxMzctYWRiZDUyNDctOTU0Ni00YjY3LWIwODgtNTEwZjU4ODc4ZmFkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE1VDExMjEyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRlM2FmMTRiNTllOGQxMmU0ZmI1MmIxN2RlNGJhOWZiZjkyYzIxY2ViMjRiM2MwYWQ1NDNkYjBjY2ZkOTVmYjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.NMyejf4DhxqkxZlYeWliT8vL6BZ9fwpoy5iZnApqtaQ">
> 最后回到当前的问题, 报错提示已经比较清楚的告诉了原因, 不知道是否有做相关的排查和确认?
> 
> <img alt="image" width="686" src="https://private-user-images.githubusercontent.com/17706099/296693614-4fb76bdb-af29-4e5e-a508-a5b9eab035dd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUzMTc5ODksIm5iZiI6MTcwNTMxNzY4OSwicGF0aCI6Ii8xNzcwNjA5OS8yOTY2OTM2MTQtNGZiNzZiZGItYWYyOS00ZTVlLWE1MDgtYTViOWVhYjAzNWRkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE1VDExMjEyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJmODAxMmVlY2Y0OTJjOWZmMDI5MTY5Mzg4N2Q3YTg3M2M1ZjMxN2Q2Y2MxZTc0ZDIxN2EzMTcwNDM0OTMwMTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xBI1pbEpmSwhqqqBkP5IvToolcmTPCRgA7_pklhzFqk">
> 如果你不熟悉可以查阅一下官方文档, 以及 loader 目录 example 文件夹中有对应本地/hdfs/多个文件的**示例**, 你可以先从示例开始熟悉 schema 定义/映射, 也可以召唤🤖提供你对应的目录/代码样本

明白！感谢您的回复！
