### ISSUE TITLE
[Question] Hubble web page Chinese display messy code

### ISSUE THREAD

**Issue by xyk98** [apache/incubator-hugegraph-toolchain#608]
### Problem Type (问题类型)

dashboard render (前端渲染问题)

### Before submit

- [X] I had searched in the [issues](https://github.com/apache/hugegraph-toolchain/issues) and found no similar issues.

### Environment (环境信息)

- Server Version: 1.2.0
- Hubble Version: 1.2.0

### Your Question (问题描述)

After deploying hugegraph and hugegraph-hubble via docker, create the Chinese attribute "姓名" on the hubble web page, and display the attribute name as "???".
Hubble web page:
<img width="1920" alt="11FD42E5-EB79-4a2e-AB3C-4B8DB8AE1CD3" src="https://github.com/apache/incubator-hugegraph-toolchain/assets/81732029/e38c8673-873b-4aae-853b-5f675298f080">
Docker:
<img width="1120" alt="F02D5D43-3CA7-416d-87F1-350FEB1AC565" src="https://github.com/apache/incubator-hugegraph-toolchain/assets/81732029/2129e11f-5e5f-43ee-9e82-9fce401658f9">
docker-compose.yml:
version: '3'
services:
  hugegraph-server:
    image: hugegraph/hugegraph:1.2.0
    container_name: hugegraph
    restart: always
    ports:
      - 18080:8080

  hugegraph-hubble:
    image: hugegraph/hubble:1.2.0
    container_name: hugegraph-hubble
    restart: always
    ports:
      - 18088:8088

**Comment by imbajin** [comment]
@xyk98 any update after @dosu 's suggestion? (Or close it if fixed)
