### ISSUE TITLE
Model is an internal package model, how should I create it Create a model when using Vertex Using Vertex [any] as a parameter, call Vertex What about Create. WithVertex

### ISSUE THREAD

**Issue by 1280019840** [apache/incubator-hugegraph-toolchain#610]
### Problem Type (问题类型)

configs (配置项 / 文档相关)

### Before submit

- [X] I had searched in the [issues](https://github.com/apache/hugegraph-toolchain/issues) and found no similar issues.

### Environment (环境信息)

- Server Version: 1.x.x
- Toolchain Version: 1.x.x
- Data Size:  xx vertices, xx edges 

### Your Question (问题描述)

Model is an internal package model, how should I create it Create a model when using Vertex Using Vertex [any] as a parameter, call Vertex What about Create. WithVertex
![image](https://github.com/apache/incubator-hugegraph-toolchain/assets/136102971/d3e36599-0c0e-4075-b83d-3273eb9159f0)
![image](https://github.com/apache/incubator-hugegraph-toolchain/assets/136102971/f4f18174-28c3-47c4-ae36-22e3fdeaf399)

**Comment by izliang** [comment]
I am aware of this issue, please give me some time. I plan to reorganize the logic and design a more user-friendly SDK.
