### ISSUE TITLE
[Question] The Huddle tool cannot connect to the graph database.

### ISSUE THREAD

**Issue by chen-xiaochen** [apache/incubator-hugegraph-toolchain#620]
### Problem Type (问题类型)

None

### Before submit

- [X] I had searched in the [issues](https://github.com/apache/hugegraph-toolchain/issues) and found no similar issues.

### Environment (环境信息)

- Server Version: 1.x.x
- Toolchain Version: 1.x.x
- Data Size:  xx vertices, xx edges 

### Your Question (问题描述)

![Clip_2024-09-04_10-25-36](https://github.com/user-attachments/assets/50ca2eff-b8a9-4e5c-b83a-ea3e95fedae3)

I am unable to use the Huddle tool to connect to the graph database, and the specific error message is shown in the figure. Can you tell me what to do?

**Comment by imbajin** [comment]
try to use docker-compose way (already provided a configuration file that you can find on the [doc](https://hugegraph.apache.org/cn/docs/quickstart/hugegraph-hubble/#21-%E4%BD%BF%E7%94%A8-docker-%E4%BE%BF%E4%BA%8E%E6%B5%8B%E8%AF%95))

**Comment by JackyYangPassion** [comment]
what's jdk version use?
