### ISSUE TITLE
[Bug] Hubble 创建属性节点中文，数据库乱码

### ISSUE THREAD

**Issue by kouhangting** [apache/incubator-hugegraph-toolchain#621]
### Bug Type (问题类型)

others (please edit later)

### Before submit

- [X] 我已经确认现有的 [Issues](https://github.com/apache/hugegraph/issues) 与 [FAQ](https://hugegraph.apache.org/docs/guides/faq/) 中没有相同 / 重复问题 (I have confirmed and searched that there are no similar problems in the historical issue and documents)

### Environment (环境信息)

- Server Version: hugegraph/hubble:latest
- Backend: mysql
- OS: 4 CPUs,8 G RAM,CentOS 7.x 
- Data Size:  0

### Expected & Actual behavior (期望与实际表现)

创建节点中文变??

使用的镜像
![image](https://github.com/user-attachments/assets/e9194d43-5236-4991-8cab-3069a5645bed)

![image](https://github.com/user-attachments/assets/cd455182-5099-498e-ba08-8e4d5cb7b433)

**Comment by insist93** [comment]
> 同样的问题，使用apache-hugegraph-hubble-incubating-1.3.0创建中文的属性，或者导入数据，中文全变成了？？？。使用restful api可以中文正常创建。请问如何解决使用hubble页面创建schame和导入数据呢中文成？？？的问题呢，谢谢！

docker 启动hugegraph/hubble的时候，加上环境变量  -e LANG=C.UTF-8 -e LANGUAGE=C.UTF-8 -e LC_ALL=C.UTF-8
